### ISSUE TITLE
r3

### ISSUE THREAD

**Issue by nobananasforyou** [Irrational-Encoding-Wizardry/vapoursynth-descale#3]
could you possibly make a build with recent changes? 

Thank you!

**Comment by Frechdachs** [comment]
I compiled a .dll for you that includes the last few commits. You can download it [here](https://u.rekt.cc/descale-65c4bff-64bit.7z) (untested). I don't want to do a proper release right now, since I'm going to push some changes probably later this month.

**Comment by nobananasforyou** [comment]
I'll just wait then. Thanks.
