### ISSUE TITLE
AVS+ version has memory leak

### ISSUE THREAD

**Issue by TbtBI** [Irrational-Encoding-Wizardry/vapoursynth-descale#5]
```
yv12 # or other supported color format
Debilinear(x, y) # any other descale function
```

Hi, when use the above code with AvsPmod/VirutalDub and continuously hit refresh (F5/F2) the used memory is growing until the editor is crashed (out of memory) or is closed.

**Comment by Frechdachs** [comment]
Thank you for reporting this issue.

**Comment by TbtBI** [comment]
Thanks for fixing it.
